-- SOURCE C:\wamp64\www\bdd\biblio-etape2-3\bibliotheque.sql
SET NAMES utf8;

DROP DATABASE IF EXISTS bibliotheque;
CREATE DATABASE bibliotheque CHARACTER SET 'utf8';

USE bibliotheque;

CREATE TABLE auteur(
        idAuteur        Int  NOT NULL AUTO_INCREMENT,
        nom             Varchar (80) NOT NULL ,
        bibliographie   Text,
	CONSTRAINT auteur_PK PRIMARY KEY (idAuteur)
)ENGINE=InnoDB;

CREATE TABLE editeur
(
   idEditeur            int not null AUTO_INCREMENT,
   nom                  varchar(80) NOT NULL,
   lien_description     varchar(200),
   CONSTRAINT editeur_PK PRIMARY KEY (idEditeur)
)ENGINE=InnoDB;

CREATE TABLE livres (
   id int NOT NULL AUTO_INCREMENT,
   titre varchar(150) NOT NULL,
   nb int NOT NULL,
   nbPages int NOT NULL,
   image varchar(150) NOT NULL,
   description text NOT NULL,
   idAuteur    Int NOT NULL ,
   idEditeur    Int NOT NULL ,
   CONSTRAINT livre_PK PRIMARY KEY (id) ,
   CONSTRAINT livre_auteur_FK FOREIGN KEY (idAuteur) REFERENCES auteur(idAuteur) ON DELETE CASCADE ,
   CONSTRAINT livre_editeur_FK FOREIGN KEY (idEditeur) REFERENCES editeur(idEditeur) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS  utilisateur (
  login varchar(50) NOT NULL,
  password varchar(100) NOT NULL,
  mail varchar(100) NOT NULL,
  role varchar(50) NOT NULL,
  image varchar(100),
  est_valide tinyint(1) NOT NULL,
  clef varchar(50), 
  PRIMARY KEY (login)
) ENGINE=InnoDB;

CREATE TABLE utilisateur_livre_emprunter(
        idEmprunt Int  Auto_increment  NOT NULL ,
        idLivre   Int NOT NULL ,
        login     Varchar (50) NOT NULL ,
        date_pret DateTime NOT NULL , 
        date_retour DateTime ,
	CONSTRAINT utilisateur_livre_emprunter_PK PRIMARY KEY (idEmprunt) ,
	CONSTRAINT utilisateur_livre_emprunter_livre_FK FOREIGN KEY (idLivre) REFERENCES livres(id) ,
	CONSTRAINT utilisateur_livre_emprunter_utilisateur0_FK FOREIGN KEY (login) REFERENCES utilisateur(login)
)ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO auteur (idAuteur, nom, bibliographie) VALUES
(1, "Melissa Da Costa", "Mélissa Da Costa est une romancière française. Après des études d’économie et de gestion, elle est chargée de communication dans le domaine de l’énergie et du climat. Elle suit également des formations en aromathérapie, naturopathie et sophrologie. La lecture fait partie de sa routine quotidienne, au milieu du sport et de l’écriture. Elle est l’autrice des Lendemains et de Tout le bleu du ciel, son premier roman porté par les libraires, salué par la presse, et couronné par le jury du Grand Prix du Livre de Poche 2020. "),
(2, "Aurélie Valognes","Aurélie Valognes, née en 1983 à Chatenay-Malabry, est une écrivaine française de littérature contemporaine. Elle publie son premier roman, Mémé dans les orties, en juillet 2014 en auto-édition puis chez Michel Lafon. Son livre se vend à plus de 300 000 exemplaires et est traduit dans plusieurs pays (États-Unis, Royaume-Uni, Allemagne, Italie, Corée, Chine, Slovénie...). En 2016, la version éditée au Livre de poche est également un best-seller. En 2016, elle sort également son second roman, Nos adorables belles-filles, aux éditions Michel Lafon. Ce roman est renommé En voiture, Simone lors de sa parution au Livre de Poche en 2017. Son dernier roman, Minute, Papillon !, paraît en avril 2017 aux éditions Fayard Mazarine."),
(3, "Michel Bussi", "Michel Bussi est un écrivain français né en 1965 en Normandie. Il connaît son premier grand succès en 2011 avec Nymphéas Noirs. Ses polars se vendent à des milliers d'exemplaires, le classant 2e auteur le plus vendu de France en 2017. Un passionné de géographie et de littérature Michel Bussi naît le 29 avril 1965 à Louviers. Dès ses 6 ans, il s'amuse à inventer des jeux de mots et des histoires. Plus tard, il dévore les romans policiers pour adolescents, comme Le Club des cinq ou Alice. À 18 ans, il entame des études de géographie à l'université de Rouen et se spécialise dans la géographie électorale. Dans les années 1990, il devient lui-même professeur de géographie à l'université et dirige jusqu'en 2016 un laboratoire de recherche du CNRS. Éminent politologue, il est régulièrement sollicité par les médias.<br>"),
(4, "Robin Norwood", "Elle s'est consacrée aux problèmes d'alcoolisme et de toxicomanie avant de se spécialiser dans la dépendance affective. L'auteure du célèbre best-seller, Les femmes qui aiment trop ainsi que des lettres de femmes qui aiment trop, ce sont des méditations quotidiennes pour les femmes qui aiment trop ( illustré par Richard Torregrossa). Les livres de Robin Norwood ont été traduits en plus de trente langues et continuer à vendre dans le monde entier. femmes qui aiment trop était un numéro un vendeur sur la liste du New York Times Best Seller avec plus de trois millions d'exemplaires imprimés dans le monde entier. "),
(5, "Albert Camus","Albert Camus est un écrivain, philosophe, romancier et nouvelliste français né le 7 novembre 1913 à Mondovi, en Algérie, alors colonie française. Il est décédé le 4 janvier 1960 à Villeblevin, dans l’Yonne. Il est connu pour son engagement dans la Résistance lors de la Seconde Guerre mondiale, et pour ses prises de position en faveur des libertés individuelles. Son premier roman, L’Étranger, publié en 1942, reste un ouvrage emblématique de la littérature du XXe siècle. Le goût de l’écriture Albert Camus naît en Algérie française en 1913, fils de Lucien Auguste Camus, caviste, et de Catherine Hélène Sintès. Il a un frère aîné, Lucien Jean Étienne. Mobilisé en tant que soldat lors de la Première Guerre mondiale, son père meurt prématurément en octobre 1914. Les deux frères deviennent pupilles de la Nation, et sont élevés tous deux auprès de leur famille maternelle. Albert Camus vit dans la pauvreté. Il se rapproche d’un de ses oncles, Gustave Acault, chez qui il effectue plusieurs séjours. Boucher anarchiste franc-maçon, celui-ci initie le jeune Albert à la littérature et éveille sa conscience politique. En parallèle, en 1923, ce dernier fait l’admiration de son instituteur Louis Germain, qui le prend sous son aile. Il lui prodigue des leçons de français et l’inscrit pour obtenir une bourse d’études. Albert Camus lui en sera reconnaissant et lui dédiera, en 1957, son prix Nobel. À la fin des années 20, il est reçu au lycée Bugeaud d’Alger, excellent établissement, où il fait la douloureuse expérience de sa différence sociale avec ses camarades. Néanmoins, passionné de philosophie, il s’investit dans ses études."),
(6, "Rupi Kaur", "Rupi Kaur est poétesse, écrivaine féministe et artiste. Née au Pendjab, elle a émigré à Toronto avec ses parents à l’âge de 4 ans. Elle a commencé à dessiner à l’âge de 5 ans, lorsque sa mère lui a tendu un pinceau et lui a dit : « dessine ce que te dicte ton cœur ». Pendant ses études de rhétorique à l’Université de Waterloo, Rupi Kaur a écrit, illustré et publié elle-même son premier recueil, lait et miel (Charleston, 2017). Depuis il est devenu un phénomène international. Son deuxième recueil, le soleil et ses fleurs, publié en 2017 en anglais, s’est tout de suite placé dans les meilleures ventes et a été adopté par les lecteurs du monde entier. À 17 ans, Rupi Kaur a réalisé sa première performance en lisant un de ces poèmes, et est tombée amoureuse de l’exercice. Elle a continué à se produire partout au Canada, fédérant autour d’elle une vraie communauté de lecteurs. Aujourd’hui ses performances sur scène sont un mélange magique entre poésie, art et théâtre. Rupi Kaur explore une grande variété de thèmes dans son travail : l’amour, la perte, les traumatismes, la guérison, la féminité, la migration, la révolution. Son travail a su trouver sa place dans le cœur de millions de personnes."),
(7, "Michael Connelly", "Michael Connelly est un écrivain américain de romans policiers, né le 21 juillet 1956 à Philadelphie, aux États-Unis. Récompensé dans de nombreux pays, Michael Connelly puise son inspiration de son expérience de journaliste, de faits divers et de sa fascination pour le rapport ambivalent de l'homme face au crime et à la justice. Ses romans, traduits en plusieurs langues, ont fait de Michael Connelly l’un des auteurs de policiers les plus connus au monde. Ses séries notables sont Mickey Haller et Jack McEvoy."),
(8, "Miguel Ruiz", "Né d'une mère curandera (guérisseuse) et d'un père nagual (chaman toltèque), il fait des études de médecine pour devenir chirurgien. Sa vie bascule lors d'une expérience de mort imminente qui l'aurait inspiré à chercher des réponses aux questions de l'existence dans la tradition toltèque. Son livre Les Quatre Accords Toltèques, publié en 1997, s'est vendu à environ 9 millions d'exemplaires, dont 8,5 millions aux États-Unis, et a été traduit en 46 langues2. Miguel Ángel Ruiz a été reçu par l'animatrice de télévision américaine Oprah Winfrey dans une émission à ce sujet. En 2002, il subit une crise cardiaque à laquelle il survit. Cette crise cardiaque et le coma qui a suivi lui ont laissé un cœur ne fonctionnant qu'à 16 % de ses capacités et en douleur constante. En 2010, il bénéficie avec succès d'une greffe du cœur. "),
(9, "Sarah Chiche", "Sarah Chiche est écrivain, psychologue clinicienne (diplômée de l'université Paris Diderot) et psychanalyste. Elle est l'auteur de deux romans : L'Inachevée (Grasset, 2008) et L'Emprise (Grasset, 2010), et de trois essais : Personne(s), d’après Le Livre de l'Intranquillité de Fernando Pessoa (Éditions Cécile Defaut, 2013), Éthique du mikado, essai sur le cinéma de Michael Haneke (PUF, 2015), Une histoire érotique de la psychanalyse : de la nourrice de Freud aux amants d'aujourd'hui (Payot, à paraître le 24 octobre 2018)."),
(10, "Victor Hugo", "Victor Marie Hugo est né à Besançon le 26 février 1802. Il est écrivain, dramaturge, poète, dessinateur, homme politique, académicien et intellectuel engagé. Il est considéré comme la plus grande figure du courant romantique en France et un des plus importants écrivains de la littérature française. En 1816, à peine âgé de 14 ans, et passionné de lettres il écrit : 'Je serai Chateaubriand ou rien'. A 19 ans, il écrit et publie ses premiers poèmes, Odes. Il est alors remarqué par le roi Louis XVIII qui lui verse une pension. Le 12 octobre 1822, il épouse Adèle Foucher avec laquelle il aura 5 enfants. En 1828 paraissent Les Orientales et Le Dernier Jour d’un condamné. A 27 ans, Victor Hugo présente une nouvelle pièce, Hernani, à la Comédie-Française. Les partisans du classicisme s’offusquent que la règle des trois unités (de temps, de lieu et d’action) ne soit pas respectée. Deux ans plus tard, en 1831, Victor Hugo publie son premier roman historique, Notre-Dame de Paris. L'ouvrage connait un très grand succès. En 1841, il est élu à l’Académie française. Sa fille Léopoldine meurt en 1843.L'écrivain est terriblement affecté par cette mort. Il s'exile après le coup d'état du 2 décembre 1851. Il met cette période d’exil à profit et continue d’écrire des recueils de poésie : Les Châtiments (1853) et Les Contemplations (1856), ce recueil est également un hommage à sa fille Léopoldine morte noyée dans la Seine. En 1862, il achève Les Misérables, qui remporte un franc succès auprès du public. A la proclamation de la République en 1870, Hugo rentre à Paris, puis le 8 février 1871, il est élu à l’Assemblée nationale. En 1876, il est élu sénateur. Le 22 mai 1885, Victor Hugo meurt d’une congestion pulmonaire à l’âge de 83 ans. Sa dépouille est exposée sous l’Arc de triomphe puis il est inhumé au Panthéon de Paris. ")
;

INSERT INTO editeur (idEditeur, nom, lien_description) VALUES
(1, 'Auto édition', 'https://copy-media.net/imprimerie/autoedition.php?gclid=Cj0KCQjw9ZGYBhCEARIsAEUXITXi5dmuL4fj8Ambfh21MtIJvjZV5hDhzVC0-BZeZt3dyKzi9FMwe8YaAs_9EALw_wcB'),
(2, 'Les Éditions Flammarion', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#2_Les_Editions_Flammarion'),
(3, 'Les éditions Milan', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#3_Les_editions_Milan'),
(4, 'Les éditions Baudelaire', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#4_Les_editions_Baudelaire'),
(5, 'Les éditions de Minuit', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#5_Les_editions_de_Minuit'),
(6, 'Hachette', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#6_Hachette'),
(7, 'Maison d’édition Le léopard masqué', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#7_Maison_drsquoedition_Le_leopard_masque'),
(8, 'Maison d’éditon Privat', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#8_Maison_drsquoediton_Privat'),
(9, 'Maison d’édition Gallimard', 'https://www.coollibri.com/blog/10-maisons-edition-populaires-2018/#1_8211_Maison_drsquoedition_Gallimard')
;

INSERT INTO `livres` (id, titre, nb, nbPages, image, description, idAuteur, idEditeur) VALUES
(1, 'Les quatre accords toltèques', 1, 1602, 'tolteques.jpg', 'Castaneda a fait découvrir au grand public les enseignements des chamans mexicains qui ont pour origine la tradition toltèque, gardienne des connaissances de Quetzacoatl, le serpent à plumes. Dans ce livre, Don Miguel révèle la source des croyances limi-tatrices qui nous privent de joie et créent des souffrances inutiles. br/ br/ Il montre en des termes très simples comment on peut se libérer du conditionnement collectif - le rêve de la planète, basé sur la peur - afin de retrouver la dimension d\'amour inconditionnel qui est à notre origine et constitue le fondement des enseignements toltèques. br/ br/ Les quatre accords proposent un puissant code de conduite capable de transformer rapidement notre vie en une expérience de liberté, de vrai bonheur et d\'amour. Le monde fascinant de la Connaissance véritable et incarnée est enfin à la portée de chacun.', 8, 1),
(2, 'Saturne', 6, 466, 'saturne.jpg', 'Sa fille est encore un bébé quand Harry meurt à 34 ans dans des circonstances tragiques. Il est issu d’une grande lignée de médecins contraints à l’exil au moment de l’indépendance de l’Algérie, et qui ont rebâti un empire médical en France. L’aîné, Armand, mettra ses pas dans ceux de sa famille. Mais la passion de Harry pour une femme à la beauté incendiaire fera voler en éclats les reliques d’un royaume où l’argent coule à flots. Saturne dépeint le crépuscule d’un monde et de ses dieux. C’est aussi un roman sur l’épreuve de nos deuils, et une grande histoire d’amour : celle d’une enfant guettée par la folie et la mort, mais qui est devenue écrivain parce que, une nuit, elle en avait fait la promesse au fantôme de son père.\n\r\n      Sarah Chiche est l’auteure de plusieurs romans et essais. Son quatrième roman, Saturne, sélectionné par les prix littéraires les plus prestigieux, a rencontré un grand succès public et critique.', 9, 2),
(3, 'Tout le bleu du ciel', 14, 642, 'ciel.jpg', 'Petitesannonces.fr : Jeune homme de 26 ans, condamné à une espérance de vie de deux ans par un Alzheimer précoce, souhaite prendre le large pour un ultime voyage. Recherche compagnon(ne) pour partager avec moi ce dernier périple.\n\r\n    Émile a décidé de fuir l’hôpital, la compassion de sa famille et de ses amis. À son propre étonnement, il reçoit une réponse à cette annonce. Trois jours plus tard, devant le camping-car acheté secrètement, il retrouve Joanne, une jeune femme coiffée d’un grand chapeau noir qui a pour seul bagage... ', 1, 1),
(4, 'Kilomètre zéro', 2, 246, 'FOISKHo.jpg', 'Maëlle, directrice financière d\'une start-up en pleine expansion, n\'a tout simplement pas le temps pour les rêves. Mais quand sa meilleure amie, Romane, lui demande un immense service - question de vie ou de mort -, elle accepte malgré elle de rejoindre le Népal. Elle ignore que l\'ascension des Annapurnas qu\'elle s\'apprête à faire sera aussi le début d\'un véritable parcours initiatique.Au cours d\'expériences et de rencontres bouleversantes, Maëlle va apprendre les secrets du bonheur profond et transformer sa vie. Mais... ', 2, 3),
(5, 'Le tourbillon de la vie', 8, 326, 'tourbillon.jpg', 'Au cours d\'un été, Arthur et son petit-fils décident de rattraper les années perdues. Plus de soixante ans les séparent, mais, ensemble, ils vont partager les souvenirs de l\'un et les rêves de l\'autre. Le bonheur serait total si Arthur ne portait pas un lourd secret…Un roman sur le temps qui passe, la transmission et les plaisirs simples qui font le sel de la vie.Entre émotion, rire et nostalgie, Aurélie Valognes nous touche en plein cœur.Humanité et bienveillance. Une parenthèse enchantée. CNews.Ce récit tendre et plein d... ', 1, 4),
(6, 'Je revenais des autres', 12, 304, 'autres.jpg', 'Philippe a quarante ans, est directeur commercial, marié et père de deux enfants. Ambre a vingt ans, n’est rien et n’a personne. Sauf lui. Quand, submergée par le vide de sa vie, elle essaie de mourir, Philippe l’envoie loin, dans un village de montagne, pour qu’elle se reconstruise, qu’elle apprenne à vivre sans lui. Pour sauver sa famille aussi.\r\n    Je revenais des autres est l’histoire d’un nouveau départ. Le feuilleton d’un hôtel où vit une bande de saisonniers tous un peu abîmés par la vie. Le récit de leurs amitiés,... ', 1, 1),
(7, 'Rien ne t\'efface', 4, 162, 'efface.jpg', 'C\'était il y a dix ans. Jour pour jour.\r\n    Un matin d\'été, sur la plage de Saint-Jean-de-Luz, le petit Esteban disparaissait.\r\n    Maddi, sa mère, ne s\'est jamais pardonné d\'avoir baissé la garde. Et puis, dix ans plus tard, même plage, même âge : ce garçon qui lui ressemble tant... Même silhouette de crevette, même maillot indigo, même tache de naissance. Sosie ? Jumeau ? Pour Maddi, aucun doute : ce garçon, ce Tom, c\'est son fils – Esteban réincarné. Pour le suivre, le protéger, elle laissera tout derrière elle. Car rien ne... ', 3, 5),
(8, 'Ces femmes qui aiment trop', 6, 248, 'trop.jpg', 'Les femmes qui aiment trop sont attirées par des hommes troubles, distants, aux humeurs changeantes, parfois alcooliques, infidèles ou obsédés par leur travail. Les femmes qui aiment trop trouvent les hommes biens plutôt ennuyeux et tombent sur des hommes qui ne parviennent pas à les aimer en retour. Les femmes qui aiment trop se sentent vides sans ces hommes mais tourmentées en leur présence. A travers des récits authentiques et personnels, Robin Norwood nous plonge au coeur des rouages psychologiques qui amènent tant de femmes à s\'enfermer dans des relations compliquées ou destructrices. Indispensable et bouleversant, ce livre aidera toutes les femmes à briser le cercle infernal de la dépendance amoureuse et de l\'échec pour redevenir elles-mêmes et s\'aimer mieux pour mieux aimer.', 4 ,6),
(9, 'L\'Étranger', 8, 420, 'etranger.jpg', 'Quand la sonnerie a encore retenti, que la porte du box s\'est ouverte, c\'est le silence de la salle qui est monté vers moi, le silence, et cette singulière sensation que j\'ai eue lorsque j\'ai constaté que le jeune journaliste avait détourné les yeux. Je n\'ai pas regardé du côté de Marie. Je n\'en ai pas eu le temps parce que le président m\'a dit dans une forme bizarre que j\'aurais la tête tranchée sur une place publique au nom du peuple français..', 5, 7),
(10, 'Lait et miel', 10, 162, 'tFhuvJz.jpg', 'lait et miel est un recueil poétique que toutes les femmes devraient avoir sur leur table de nuit ou la table basse de leur salon. Accompagnés de ses propres dessins, ses poèmes, d\'une honnêteté et d\'une authenticité rares, se lisent comme les expériences collectives et quotidiennes d\'une femme du... ', 6, 8),
(11, 'Séquences mortelles', 18, 468, 'mortelles.jpg', 'L’illustre Jack McEvoy, devenu journaliste pour un site web de défense des consommateurs, a eu raison de bien des assassins. Jusqu\'au jour où il est accusé de meurtre par deux inspecteurs du LAPD. Et leurs arguments ont du poids : il aurait tué une certaine Tina Portrero, avec laquelle il a effectivement passé une nuit. Malgré les interdictions de la police et de son propre patron, il enquête et découvre que d\'autres femmes sont mortes de la même et parfaitement horrible façon : le cou brisé. Le tueur, il le comprend aussi,... ', 7, 6),
(12, 'Le temps est assassin', 12, 489, 'le-temps.jpg', 'Un parfum de maquis plane sur Le Temps est assassin, le dernier livre de Michel Bussi… Autour du parcours de Clothilde, unique survivante d’un accident de voiture survenu en Corse il y a vingt-cinq ans, l’auteur tisse une intrigue haletante où l’ambiance particulière de l\’Île de Beauté tient le rôle d\’un personnage à part entière. Confrontant son héroïne ordinaire aux sursauts du passé et aux mystères du présent, l’écrivain poursuit son parcours sans faute, avec un nouveau thriller familial aussi efficace que crédible.', 3, 1),
(13, 'Gravé dans le sable', 6, 678, '2ibMee5.jpg', 'Michel Bussi nous entraine dans une grande aventure humaine avec Gravé dans le sable, qui paraît en poche. Il y a tous les ingrédients pour séduire le plus grand nombre : de l\'histoire (ça commence en juin 1944, au moment du Débarquement), de la romance (l\'amour entre Lucky et Alice qui traverse les années, malgré la disparition) et du thriller (et si Lucky avait passé un pacte dont il n\'aurait jamais voulu connaître l\'existence ?). Entre la France et les Etats-Unis, l\'auteur nous emmène dans une épopée passionnante que... ', 3, 6),
(14, 'Un avion sans elle', 14, 358, '3VF1Bv6.jpg', "23 décembre 1980. Un crash d'avion dans le Jura. Une petite libellule de 3 mois tombe du ciel, orpheline. Deux familles que tout oppose se la disputent. La justice tranche : elle sera Émilie Vitral. Aujourd'hui, elle a 18 ans, la vie devant elle mais des questions plein la tête. Qui est-elle vraiment ? Dix-huit ans que Crédule Grand-Duc, détective privé, se pose la même question. Alors qu'il s'apprête à abandonner, la vérité surgit devant ses yeux, qu'il referme aussitôt, assassiné. Il ne reste plus à Émilie qu'un vieux... ", 3, 6),
(15, "J'ai dû rêver trop fort", 8, 268, 'J-ai-du-rever-trop-fort.jpg', "Montréal, San Diego, Barcelone, Jakarta... Le quarté dans l'ordre. Sur le chemin de Roissy, Nathy s'interroge. Quelles sont les probabilités pour qu'on lui attribue, précisément, ces quatre destinations – les mêmes qu'il y a vingt ans ? Car l'hôtesse de l'air n'a jamais oublié cette parenthèse enchantée – quelques accords de guitare, un regard intense sous une casquette écossaise... Un rêve trop grand, trop fort – vingt ans déjà ! Quel dieu farceur s'ingénie donc ainsi à multiplier les coïncidences ? Quel dieu cruel, à... ", 3, 6),
(16, 'Code 612 Qui a tué le Petit Prince ?', 8, 624, 'code-612.jpg', "Qui mieux que Michel Bussi pour imaginer une enquête passionnante sur le mystère et les ombres du Petit Prince et de son créateur Saint-Exupéry ? Roman à clé, jeu de piste, hommage, Code 612 Qui a tué le Petit Prince? célèbre les 75 ans du Petit Prince. Un livre indispensable pour les amoureux du conte et de son auteur. Avec la signature Bussi : ludique, poétique, surprenante. Il est le livre le plus traduit au monde, après la Bible, et l'un des plus vendus, conte étrange et fascinant. Il est l'incarnation... ", 3, 6),
(17, 'Nymphéas noirs', 1, 384, 'OrXklkp.jpg', "Le jour paraît sur Giverny. Du haut de son moulin, une vieille dame veille, surveille. Le quotidien du village, les cars de touristes... Des silhouettes et des vies. Deux femmes, en particulier, se détachent : l'une, les yeux couleur nymphéa, rêve d'amour et d'évasion ; l'autre, onze ans, ne vit déjà que pour la peinture. Deux femmes qui vont se trouver au cœur d'un tourbillon orageux. Car dans le village de Monet, où chacun est une énigme, où chaque âme a son secret, des drames vont venir diluer les illusions et raviver... ", 3, 6),
(18, 'Au soleil redouté', 6, 212, 'Au-soleil-redoute.jpg', "Elles étaient cinq... Cinq lectrices fidèles et auteures en herbe qu'un concours expédie, pour une semaine, au paradis du Pacifique, les îles Marquises. Au programme, atelier d'écriture sous la baguette du grand écrivain Pierre-Yves François, et puis... tout le reste, bien sûr : découverte de l'île – ce joyau fauve cher à Gauguin et chanté par Brel –, sable noir, folklore local, tatouages raffinés, disparitions mystérieuses et meurtres en série... Sous l'œil placide des grands tikis, quelqu'un tue au soleil. Qui sera la... ", 3, 6),
(19, 'Ne lâche pas ma main', 2, 823, 'NtzM44n.jpg', "Un couple d'amoureux dans les eaux turquoise de l'île de La Réunion. Farniente, palmiers, soleil. Un cocktail parfait. Pourtant, le rêve tourne court. Quand Liane disparaît de l'hôtel, son mari, Martial, devient le coupable idéal. Désemparé, ne sachant comment prouver son innocence, il prend la fuite avec leur fille de 6 ans. Pour la police, cela sonne comme un aveu : la course-poursuite, au cœur de la nature luxuriante de l'île, est lancée. Bussi développe tout son talent en suspense et en personnage à fendre l... ", 3, 6),
(20, "N'oublier jamais", 1, 478, '6ySqUk7.jpg', "Michel Bussi est un maître du thriller français qui confirme son statut à chaque nouveau roman. N'oublier jamais, ne déroge pas à la règle. On est immédiatement happé par cette histoire de faux semblants et par la science du suspense de l'auteur. Encore une fois, la construction narrative et la consistance des personnages, surtout celui tout en nuances et zones d'ombres de Jamal, sont d'une diabolique efficacité. On frissonne, on s'angoisse. et on en redemande. Le contrat est largement rempli.", 3, 6),
(21, "Cent poèmes de Victor Hugo", 8, 869, 'GlIRbx4.jpg', "Ces Cent poèmes de Victor Hugo, réunis par Albine Novarino-Pothier et Béatrice Mandopoulos, sont illustrés de photos d'aujourd'hui (Michel Maïofiss). Ils sont l'essence de la poésie et l'essence même de la vie, la vraie, la seule qui vaille d'être vécue...Au-delà de nos souvenirs de récitations d'enfance, nous avons ardemment souhaité qu'au fil des pages revive l'homme – l'homme dont les poèmes sont le miroir des émotions sur toute la gamme des sentiments qu'il vécut : des premiers émois amoureux dans une Espagne vibrante... ", 10, 4),
(22, "Les Misérables - Intégrale", 4, 520, 'Les-Miserables-Integrale.jpg', "Peut-on imaginer un monde sans Jean Valjean, Cosette, Gavroche, Javert ou Fantine, à jamais vivants au Panthéon de l'esprit humain ? En 1862 paraissent Les Misérables, qui désignent toutes les vicitmes d'un ordre social dont Victor Hugo condamne les injustices. Immense épopée populaire, le roman est emporté dans l'air de Paris et de ses bas-fonds, chargé de l'odeur des barricades et de la Révolution. Il deviendra l'une des oeuvres les plus lues dans le monde. On dit que lorsque les... ", 10, 4),
(23, "Notre-Dame de Paris", 5, 960, 'GLmjFVO.jpg', "Il était là, grave, immobile, absorbé dans un regard et dans une pensée. Tout Paris était sous ses pieds, avec les mille flèches de ses édifices et son circulaire horizon de molles collines, avec son fleuve qui serpente sous ses ponts et son peuple qui ondule dans ses rues, avec le nuage de ses fumées, avec la chaîne montueuse de ses toits qui presse Notre-Dame de ses mailles redoublées. Mais dans toute cette ville, l'archidiacre ne regardait qu'un point du pavé : la place du Parvis ; dans toute cette foule, qu'une figure... ", 10, 4),
(24, "Le Dernier Jour d'un condamné", 6, 489, 'Le-Dernier-Jour-d-un-condamne.jpg', "LES GRANDS TEXTES DU XIXe SIÈCLE : Encore six heures et je serai mort. Est-il bien vrai que je serai mort avant la fin du jour ? Bientôt, sa tête roulera dans la sciure. Jugé, emprisonné, enchaîné, il attend dans l'épouvante. J'ai peur – et notre peur grandit avec la sienne. L'aumônier viendra, puis les assistants du bourreau. Il montera dans la charrette, traversera la foule hideuse. Au bout de la marche au supplice, l'apparition de la guillotine. On dit qu'on ne souffre pas, que c'est une fin douce, mais qui le sait... ", 10, 4),
(25, "Les Contemplations", 2, 869, 'les-Contemplations.jpg', "Les Contemplations, que Hugo fait paraître en 1856, sont à un double titre marquées par la distance et la séparation : parce quele proscrit qui, dans Châtiments, vient defustiger Napoléon III, est en exil à Guernesey ;mais aussi parce que le recueil, en son centre, porte la brisure du deuil, et ses deux parties – « Autrefois », «Aujourd’hui» –sont séparées par la césure tragique de l’année 1843 où Léopoldine, la fille de Hugo, disparut noyée. La parole poétique prend naissance dans la mort, et « ce livre », nous dit l... ", 10, 4),
(26, "Les Travailleurs de la mer", 2, 269, 'Les-Travailleurs-de-la-mer.jpg', "Pour pouvoir reconstruire un nouveau bateau à vapeur après le naufrage de La Durande, il faudrait sauver la précieuse machine du navire dont le constructeur est mort. Donc qu’un homme seul, matelot mais aussi forgeron, ait l’audace de se risquer plusieurs jours jusqu’aux rochers Douvres où repose l’épave – et d’affronter la mer. L’homme qui accepterait ce péril seraitplus qu’un héros. «Je l’épouserais», dit alors Déruchette, la nièce de l’armateur. Et parce qu’il s’est épris de la jeune fille, Gilliatt va tenter l... ", 10, 4),
(27, "L'Homme qui Rit", 1, 980, 'L-Homme-qui-Rit.jpg', "L'Angleterre a connu, cent quarante ans avant la France, une révolution, un parlement régicide, une république et une restauration fertile en règlements de comptes. Victor Hugo a choisi ce dernier épisode pour brosser un tableau épique de l'aristocratie anglaise à travers la destinée extraordinaire de Gwynplaine, l'Homme qui Rit.À la fois roman d'aventures, exposé historique et social, drame injouable et poème visionnaire, ce roman est le plus fou de tous les romans de Hugo. C'est aussi le plus riche de toutes les... ", 10, 4),
(28, "Claude Gueux", 4, 456, 'Claude-Gueux.jpg', "Un homme nommé Claude Gueux, pauvre ouvrier, vivait à Paris en 1831. Il avait avec lui une fille qui était sa maîtresse et un enfant de cette fille... Il était capable, habile, intelligent, fort mal traité par l'éducation, fort bien traité par la nature, ne sachant pas lire mais sachant penser. Un hiver, l'ouvrage manqua. L'homme, la fille et l'enfant eurent froid et faim. L'homme vola. Il en résulta trois jours de pain et de feu pour la femme et pour l'enfant et cinq ans de prison pour l'homme. Il fut envoyé faire son... ", 10, 4),
(29, "Choses vues", 2, 264, 'Choses-vues.jpg', "Choses vues, entendues, notées sur le vif en forme de brèves, de caricatures ou de longs portraits, de récits bouleversants, d'enquêtes, de grands moments qui appartiennent désormais à l'histoire nationale, mais aussi de mots d'esprit, d'expressions glanées dans la rue - voici le siècle de Hugo. Cet extraordinaire recueil, constitué après la mort de Victor Hugo et sur sa recommandation, est fait de pièces et de morceaux recousus à partir de ses Carnets, de son Journal, de ses livres de comptes, de ce qu'il appelait lui-même... ", 10, 4),
(30, "Lucrèce Borgia", 1, 234, 'Lucrece-Borgia.jpg', "Indifférente à la haine de l'Italie entière, Lucrèce Borgia parade au carnaval de Venise. Qui pourrait inquiéter cette femme de pouvoir qui baigne dans l'adultère, l'inceste et le crime ? Elle a peur cependant, et tremble pour un simple capitaine qu'elle cherche parmi la foule. Il se nomme Gennaro. Il est amoureux d'elle, lui qui tient les Borgia en aversion et insulte leur blason. Or Gennaro n'est autre que le fils de Lucrèce, né de ses amours incestueuses avec son propre frère,... ", 10, 4),
(31, "Ruy Blas", 4, 458, 'M8KSjuq.jpg', "À la cour des Habsbourg d'Espagne, alors que le règne de Charles II touche à sa fin, un valet revêt les habits de son maître et accède aux plus hautes sphères du pouvoir. Très vite, l'homme du peuple se révèle un être d'exception et suscite l'admiration de la reine dont il est secrètement amoureux. Mais le laquais, instrument d'une vengeance infâme, s'expose malgré lui à une chute funeste.En 1838, cinq ans après l'immense succès de Lucrèce Borgia, Hugo met en scène un royaume qui expire et fait d'un manant l'égal des...", 10, 4),
(32, "Victor hugo, les dessins", 2, 356, 'Victor-hugo-les-deins.jpg', "Si Hugo n'a guère voulu montrer ses dessins de son vivant, des artistes phares ont depuis reconnu son audace, tel André Breton, qui y vit des tableaux où la plus puissante imagination se donne cours. Les Maisons de Victor Hugo, Paris/Guernesey ; conservent aujourd'hui plus de sept cents feuilles, parmi lesquelles de très nombreux chefs-d'oeuvre. Gérard Audinet, leur directeur, s'attache ici à suivre pas à pas, année après année, l'intense fièvre graphique du poète, faisant de cette étude une véritable monographie. Cet... ", 10, 4),
(33, "Marion de Lorme", 2, 356, 'Marion-de-Lorme.jpg', "Alors que la querelle du Cid fait rage et qu'un décret de Richelieu, ministre de Louis XIII, a interdit les duels, la célèbrecourtisane parisienne, Marion de Lorme, se réfugie à Blois, à l'abri des regards : bien décidée à changer de vie, elle attend son amant, Didier, qui ne la connaît pas encore sous son vrai nom, mais sous celui de Marie. Et pour cause : il exècre Marion de Lorme, une femme, de corps belle, et de coeur difforme. Rien n'aurait pu assombrir cette histoire d'amour, si Didier n'avait pas provoqué en duel... ", 10, 4),
(34, "Carnets d'amour à Juliette Drouet", 2, 356, 'Carnets-d-amour-a-Juliette-Drouet.jpg', "Nous pensions avoir tout lu de Victor Hugo. Ses vers, appris par des générations d'élèves. Ses pièces, jouées par des générations d'acteurs. Ses romans, lus par des générations de lecteurs à travers le monde. Et sans doute un grand écrivain français, qui eut droit aux honneurs nationaux, appartient à chacun. Mais nous connaissons moins le Victor Hugo intime. Nous l'avions vu en père inconsolable après la mort de sa fille en 1843, en grand-père débonnaire en 1877. Nous le découvrons ici, à trente et un ans, en amant... ", 10, 4),
(35, "La Ritournelle", 3, 186, 'OpqjIEf.jpg', "Dans certaines familles, les repas de fêtes se suivent et se ressemblent : mêmes plats, mêmes convives, mêmes discussions. Sauf cette année. Il suffit d’un rien pour que les bonnes manières volent en éclat : non-dits, vieilles rancunes et mauvaise foi vont transformer le dîner de fête en un règlement de compte en bonne et due forme. Et si les repas de famille étaient enfin l’occasion de se dire les choses ? Des dialogues enlevés, des personnages hauts en couleur, Un roman drôle et jouissif ! Avec son talent unique pour... ", 1, 4),
(36, "Né sous une bonne étoile", 2, 118, 'Bt83V1j.jpg', "Sans être vraiment fâché avec l’école, Gustave peine à y trouver sa place. En classe, il observe les oiseaux dans la cour, rêvasse, scrute les aiguilles de la pendule. Il aimerait bien rapporter des bonnes notes à sa mère au lieu des habituelles convocations du directeur. Pourtant, Gustave est travailleur. Il passe beaucoup de temps sur ses devoirs, mais les leçons ne rentrent pas. Certains enseignants commencent même à le prendre en grippe et à le croire fainéant. Et à force d'entendre qu'il est un cancre, Gustave finit...", 1, 4),
(37, "Au petit bonheur la chance", 3, 146, 'Au-petit-bonheur-la-chance.jpg', "1968. Jean a six ans quand il est confié du jour au lendemain à sa grand-mère, Pour l’été. Pour toujours. Il n’a pas prévu ça. Elle non plus. Mémé Lucette n’est pas commode, mais dissimule un cœur tendre. Jean, véritable moulin à paroles, est un tourbillon de fraîcheur pour celle qui vivait auparavant une existence paisible, rythmée par ses visites au cimetière et sa passion pour le tricot. Chacun à une étape différente sur le chemin de la vie – elle a tout vu, il s’étonne de tout –, Lucette et Jean vont s’apprivoiser en...", 1, 4),
(38, "La Cerise sur le gâteau", 5, 224, '2WganRG.jpg', "La vie est mal faite : à trente-cinq ans, on n'a le temps de rien ; à soixante-cinq ans, on a du temps, mais encore faut-il savoir quoi en faire... Bernard et Brigitte en savent quelque chose. Depuis qu'elle a cessé de travailler, Brigitte profite de sa liberté retrouvée et s’investit dans son rôle de grand-mère. Pour elle, ce n'est que du bonheur. Jusqu'au drame : la retraite de son mari. Car, pour Bernard, troquer ses costumes contre des pantoufles, hors de question ! Ajoutez à cela des enfants au bord de la crise de...", 1, 4),
(39, "Minute, papillon !", 4, 234, 'vohl005.jpg', "Rose, 36 ans, mère célibataire, est une femme dévouée qui a toujours fait passer les besoins des autres avant les siens. Après avoir perdu son père et son emploi, la jeune femme apprend que Baptiste, son fils unique de 18 ans, quitte la maison. Son monde s’effondre. Cette ex-nounou d’enfer est alors contrainte d’accepter de travailler comme dame de compagnie pour une vieille dame riche et toquée, Colette, et son insupportable fille, la despotique Véronique. Et si, contre toute attente, cette rencontre atypique allait...", 1, 4),
(40, "En voiture, Simone !", 3, 286, 'En-voiture-Simone.jpg', "Pour une comédie familiale irrésistible, il vous faut : un père, despotique et égocentrique, Jacques.  Une mère, en rébellion après quarante ans de mariage, Martine.  Leurs fils, Matthieu, éternel adolescent mais bientôt papa de trois enfants  ; Nicolas, chef cuisinier le jour et castrateur tout le temps  ; Alexandre, rêveur mou du genou. Et...  trois belles-filles  délicieusement insupportables ! Stéphanie, mère poule angoissée  ; Laura, végétarienne angoissante  ; Jeanne, nouvelle pièce rapportée, féministe et déboussolée...", 1, 4),
(41, "Mémé dans les orties", 6, 542, 'Meme-dans-les-orties.jpg', "Premier roman et premier succès pour Aurélie Valognes ! Avec son style alerte et les émotions universelles qu'il porte, Mémé dans les orties a déjà conquis de nombreux lecteurs à travers le monde. On ne peut retenir ses larmes ni ses éclats de rire en lisant l'histoire - contée toute en finesse - de Juliette et Béatrice, une fillette et sa grand-mère réussissant l'exploit d'apprivoiser un vieux misanthrope. La leçon de vie est si belle qu'on se dit qu'il n'est jamais trop tard pour ouvrir son cour et commencer à être...", 1, 4),
(42, "La femme mariée et le sexe", 4, 234, 'OttefN2.jpg', "La révolution du mariage est en route : à sa tête, des femmes modernes, en totale rupture avec leurs mères et leurs grand-mères, pour qui l'engagement n... ", 4, 7),
(43, "Las mujeres que aman demasiado", 2, 102, 'jxElcdB.jpg', "En este libro la autora ofrece un camino para que todas aquellas mujeres que aman demasiado puedan amarse a sí mismas y establezcan una relación de pareja sana, feliz y duradera.Cómo cambiar nuestra manera de amar y así dejar de sufrir.«Cuando estar enamorada significa sufrir, es que estamos amando demasiado. Cuando la mayoría de nuestras conversaciones con amigas íntimas son acerca de él, de sus problemas, ideas, acciones y sentimientos, cuando casi todas nuestras frases comienzan con él..., es que estamos amando... ", 4, 7),
(44, "¿Por qué a mí?", 1, 96, 'por-que-a-mi.jpeg', "Un título para hombres y mujeres que desean curar las heridas más profundas del corazón.Una guía para responder a las preguntas más difíciles que nos plantea la vida.Con su célebre libro Las mujeres que aman demasiado, Robin Norwood cambió definitivamente la manera de pensar acerca de las relaciones de pareja e instauró una nueva actitud en las mujeres que sufrían por amor.En ¿Por qué a mí? Robin Norwood enseña a hombres y mujeres a comprender la forma de enfrentarnos a las adversidades y a modificarla cuando nos hace... ", 4, 7),
(45, "Meditaciones para mujeres que aman demasiado", 2, 124, 'Meditaciones-para-mujeres-que-aman-demasiado.jpg', "Robin Norwood intenta hacer que las mujeres tomen conciencia de su dependencia en el terreno amoroso y aprendan el camino para liberarse de una verdadera esclavitud.Con Las mujeres que aman demasiado Robin Norwood creó una nueva perspectiva acerca del tema del amor adictivo, los sufrimientos que provoca y la dificultad para salir de la trampa que supone una relación de pareja destructiva.Su libro ayudó a incontables mujeres, atadas a un amante o marido que las maltrataba emocional e incluso físicamente, a tomar conciencia...", 4, 7),
(46, "Donne che amano troppo", 1, 86, 'Donne-che-amano-troppo.jpg', "Perché amare diviene “amare troppo”, e quando questo accade? Perché le donne a volte pur riconoscendo il loro partner come inadeguato o non disponibile non riescono a liberarsene? Mentre sperano o desiderano che lui cambi, di fatto si coinvolgono sempre più profondamente in un meccanismo di assuefazione. Donne che amano troppo, un bestseller che ha raggiunto il record di cinque milioni di copie vendute, offre una casistica nella quale sono lucidamente individuate le ragioni per cui molte donne si innamorano dell’uomo...", 4, 7),
(47, "La Peste", 2, 328, 'XGuJn1U.jpg', "Sur le pont, je passai derrière une forme penchée sur le parapet, et qui semblait regarder le fleuve. De plus près, je distinguai une mince jeune femme, habillée de noir. Entre les cheveux sombres et le col du manteau, on voyait seulement une nuque, fraîche et mouillée, à laquelle je fus sensible. Mais je poursuivis ma route, après une hésitation. [...] J'avais déjà parcouru une cinquantaine de mètres à peu près, lorsque j'entendis le bruit, qui, malgré la distance, me parut formidable dans le silence nocturne, d'un corps...", 5, 5),
(48, "Le premier homme", 3, 412, 'Le-premier-homme.jpg', "En somme, je vais parler de ceux que j'aimais, écrit Albert Camus dans une note pour Le premier homme. Le projet de ce roman auquel il travaillait au moment de sa mort était ambitieux. Il avait dit un jour que les écrivains gardent l'espoir de retrouver les secrets d'un art universel qui, à force d'humilité et de maîtrise, ressusciterait enfin les personnages dans leur chair et dans leur durée.Il avait jeté les bases de ce qui serait le récit de l'enfance de son premier homme. Cette rédaction initiale a un caractère...", 5, 5),
(49, "Le mythe de Sisyphe", 1, 542, 'Le-mythe-de-Sisyphe.jpg', "Il n'y a qu'un problème philosophique vraiment sérieux : c'est le suicide. Avec cette formule foudroyante, qui semble rayer d'un trait toute la philosophie, un jeune homme de moins de trente ans commence son analyse de la sensibilité absurde. Il décrit le mal de l'esprit dont souffre l'époque actuelle : L'absurde naît de la confrontation de l'appel humain avec le silence déraisonnable du monde.", 5, 5),
(50, "L'Homme révolté", 4, 618, 'L-Homme-revolte.jpg', "Je me révolte, donc nous sommes, affirme Albert Camus. La révolte est le seul moyen de dépasser l'absurde. Mais le véritable sujet de L'homme révolté est comment l'homme, au nom de la révolte, s'accommode du crime, comment la révolte a eu pour aboutissement les États policiers et concentrationnaires du XX? siècle. Comment l'orgueil humain a-t-il dévié ?De violentes polémiques ont accompagné la sortie de cet essai. Les contemporains de Camus n'étaient pas mûrs pour admettre des vérités qui s'imposent désormais et mettent L...", 5, 5),
(51, "La mort heureuse", 2, 323, 'La-mort-heureuse.jpg', "Je suis certain qu'on ne peut être heureux sans argent. Voilà tout. Je n'aime ni la facilité ni le romantisme. J'aime à me rendre compte. Eh bien, j'ai remarqué que chez certains êtres d'élite il y a une sorte de snobisme spirituel à croire que l'argent n'est pas nécessaire au bonheur. C'est bête, c'est faux, et dans une certaine mesure, c'est lâche. En 1938, Albert Camus abandonne son premier roman, La mort heureuse, pour commencer à rédiger L'étranger. Ce premier projet romanesque, publié à titre posthume, est riche...", 5, 5),
(52, "Correspondance", 2, 346, 'fPXVoyI.jpg', "Tu es entrée, par hasard, dans une vie dont je n'étais pas fier, et de ce jour-là quelque chose a commencé de changer. J'ai mieux respiré, j'ai détesté moins de choses, j'ai admiré librement ce qui méritait de l'être. Avant toi, hors de toi, je n'adhérais à rien. Cette force, dont tu te moquais quelquefois, n'a jamais été qu'une force solitaire, une force de refus. Avec toi, j'ai accepté plus de choses. J'ai appris à vivre. C'est pour cela sans doute qu'il s'est toujours mêlé à mon amour une gratitude immense. Pendant...", 5, 5),
(53, "L'été", 4, 654, 'L-ete.jpg', "Qu'il suive le fil d'Ariane sur les traces du Minotaure pour évoquer Oran et ses alentours, qu'il revisite le mythe de Prométhée à la lumière de la violence du monde moderne, ou qu'il rêve à la beauté d'Hélène et de la Grèce, Albert Camus nous entraîne tout autour de la Méditerranée et de ses légendes. Un court recueil de textes lyriques et passionnés pour voyager de l'Algérie à la Grèce en passant par la Provence.", 5, 5),
(54, "Incendie nocturne", 8, 384, 'uSrdjQo.jpg', "ohn Jack Thompson était le mentor de Bosch à ses débuts, celui qui lui a appris à toujours prendre une affaire personnellement et à déployer tous ses efforts pour la résoudre. À la mort de Thompson, sa veuve confie à Bosch un dossier volé par son mari aux scellés avant sa retraite. Il s'agit d'une affaire non résolue : un jeune homme abattu dans une ruelle coupe-gorge de Los Angeles des années plus tôt. Bosch demande l'aide de Renée Ballard, déjà fort occupée au quart de nuit à Hollywood après qu'un sans-abri a été...", 7, 1),
(55, "Nuit sombre et sacrée", 2, 246, 'Nuit-sombre-et-sacree.jpg', "En revenant au commissariat d’Hollywood après une mission de son quart de nuit, l’inspectrice Renée Ballard tombe sur un inconnu en train de fouiller dans les meubles à dossiers. L’homme, un certain Harry Bosch, est un ancien des Homicides du LAPD qui a repris du service au commissariat de San Fernando, où il travaille sur une affaire qui le ronge depuis des années. Après l’avoir chassé, Ballard, intriguée, ouvre le dossier qu’il feuilletait, se renseigne... et décide de l’aider. La mort de Daisy Clayton, une fugueuse de...", 7, 9),
(56, "En attendant le jour", 4, 680, 'En-attendant-le-jour.jpg', "Reléguée au quart de nuit du commissariat d’Hollywood, l’inspectrice Renée Ballard se lance dans des enquêtes qu’elle n’a pas le droit de mener à leur terme. Le règlement l’oblige en effet à les confier aux inspecteurs de jour dès la fin de son service. Mais, une nuit, elle tombe sur deux affaires qu’elle refuse d’abandonner : le tabassage d’un prostitué laissé pour mort dans un parking, et le meurtre d’une jeune femme lors d’une fusillade dans un night-club. En violation de toutes les règles et contre la volonté même de...", 7, 9),
(57, "Deuil interdit ", 1, 213, 'Deuil-interdit.jpg', "Los Angeles, été 1988. Les tensions raciales sont au plus haut dans la Cité des Anges et Rebecca Verloren, une jeune métisse de seize ans, est retrouvée abattue d’un seul coup de feu tiré en pleine poitrine. À l’époque, les inspecteurs du LAPD concluent au suicide. Dix-huit ans plus tard, Harry Bosch, affecté à l’unité des Affaires non résolues, reprend le dossier à la suite d’une analyse ADN aux conclusions troublantes : la jeune métisse aurait été tuée par un suprémaciste blanc. Bosch, pour qui une ville qui oublie ses...", 7, 1),
(58, "Une vérité à deux visages", 2, 234, 'Une-verite-a-deux-visages.jpg', "Travaillant toujours bénévolement aux affaires non résolues pour la police de San Fernando, Harry Bosch est appelé sur une scène de crime dans une pharmacie. Les deux employés, père et fils, viennent d'être assassinés par des tueurs à gages, et toutes les pistes s'orientent vers un trafic de médicaments antidouleurs qui, pris inconsidérément, se transforment en véritables drogues. Bosch n'hésite pas une seconde et se lance dans l'enquête. Mais voilà qu'il est soudain accusé par la police de Los Angeles d'avoir, trente ans...", 7, 9),
(59, "Séquences mortelles", 4, 568, 'WLwph7D.jpg', "L’illustre Jack McEvoy, maintenant journaliste au Fair Warning, un site Web de défense des consommateurs, a eu raison de bien des assassins. Jusqu’au jour où il est accusé de meurtre par deux inspecteurs du LAPD. Et leurs arguments ont du poids : il aurait tué une certaine Tina Portrero avec laquelle il a effectivement passé une nuit, et qu’il aurait harcelée en ligne. Malgré les interdictions de la police et de son propre patron, il enquête et découvre que d’autres femmes sont mortes de la même et parfaitement horrible...", 7, 9)
-- (59, "", 4.78, 568, '', "", 0, 7, 9)
;

INSERT INTO `utilisateur` (`login`, `password`, `mail`, `role`, `image`, `est_valide`) VALUES
('admin','$2y$10$Z.NV5jhY4Emy2XRJlbVnJ.uWsmeJkOB06xKq5Eb8ml9QapXUOJOmm','ctouti@gmail.com','administrateur','profils/profil.png',1),
('abonne', '$2y$10$pF2pLd2Cs8tuQv2kKonj/ujHiQf6s.Tuo5ZmKxcy927GN11iyxpIC', 'ctouti@gmail.com', 'abonne', 'profils/profil.png', 1),
('hugo', '$2y$10$Fapf2t9/GpnUK/k.JCWH3eOU/DezeKmMW0ed9dGvWkKhdp1dEWj/O', 'ctouti@gmail.com', 'abonne', 'profils/profil.png', 1),
('tophe', '$2y$10$1wRqiw9qcMXT2lD69DQgpetpq2GuzNN8pqLqa0hFQAg9kL6PiIKYa', 'ctouti@gmail.com', 'abonne', 'profils/profil.png', 1);
COMMIT;

